### ISSUE TITLE
Syntax color issue

### ISSUE THREAD

**Issue by syedsimanta03** [attitudeanil/Evans-Dark-Theme#1]
```
            <div class="stage__text">
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Cupiditate, vel. Vel qui ipsum eum similique reiciendis dicta
                dignissimos sed ipsa.
              </p>
            </div>
```
            Hey man. Everything looks good. But can you please change the solid white color for text like lorem ipsum above? Maybe make it a bit greish color that doesn't hurt eyes. Also make deep green or something for class name like "stage__text" & same color when selected in JavaScript
            
            const leftImages = gsap.utils.toArray('.stage__text')

**Comment by anilbeesetti** [comment]
Thanks man for your suggestion. I've released new update with your suggestion in mind. I have used a greish color. If it is not sufficient you can add this line to your settings.json file.

```
"workbench.colorCustomizations": {
     "editor.foreground": "YOUR PREFERRED COLOR"
 },

 ```
